# This is my journy in https://projecteuler.net/ problems

# Problem1
## Multiples of 3 or 5
### If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.Find the sum of all the multiples of 3 or 5 below 1000.

In [2]:
result =[]
for i in range(1000):
    if i%5==0:
        result.append(i)
    elif i%3==0:
        result.append(i)
sum(result)

233168

# Problem2
## Even Fibonacci numbers
### Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

### 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

### By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [8]:
first=1
second=2
arr=[2]
while (first+second)<4000000:
    temp=first+second
    first=second
    second=temp
    if temp%2==0:
        arr.append(temp)
sum(arr)

4613732